---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - Laura Lee-Chu
  - Will Davidson
  - Syed Hassan
thanks: "Code and data are available at: LINK."
date: "`r Sys.time()`"
date-format: "D MMMM YYYY"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| echo: false
#| warning: false
#| message: false

library(tidyverse)
library(here)
library(readr)
library(readxl)
library(kableExtra)
library(scales)
library(knitr)
library(janitor)

```



```{r}
#| echo: false
#| warning: false

import_clean_data <- read_csv(
  here::here("outputs/data/clean_data.csv"),
  show_col_types = FALSE
)

check_unique_01 <- import_clean_data |>
  select(degree) |> 
  unique()

filter_degree <- import_clean_data |>
  filter(degree != ".d:  Do not Know/Cannot Choose") |> 
  filter(degree != ".n:  No answer")

# make sure the data is filtered from the arguments above
check_unique_02 <- filter_degree |>
  select(degree) |> 
  unique()
  
count_people_degree <- filter_degree |> 
  select(year, degree) |>
  group_by(year) |> 
  count(degree)


```


```{r}
#| echo: false
#| warning: false
#| label: education_total
#| fig-cap: Education of the population with classification.
#| fig-align: center
#| fig-width: 5.5

count_people_degree |>
  mutate(across(degree, factor, levels=c("Graduate",
                                         "Bachelor's",
                                         "Associate/junior college",
                                         "High school",
                                         "Less than high school"))) |> 
  ggplot(aes(x = year, y = n)) +
  scale_x_continuous(breaks = seq(1998, 2018, 2)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 65, vjust = 0.6)) +
  geom_point() +
  geom_line() +
  facet_wrap(
    ~degree,
    ncol = 2,
    scale="free_y") +
  labs(
    x = "year",
    y = "n"
  )
```


```{r}
#| echo: false
#| warning: false
#| label: education_by_sex
#| fig-cap: Education levels by sex.
#| fig-align: center
#| fig-width: 6


by_sex <- filter_degree |> 
   select(degree, sex) |>
   group_by(degree, sex) |> 
   count(degree)

by_sex |>
   select(degree, n , sex) |>
   ggplot(aes(x = degree, y = n, fill = sex)) +
   scale_y_continuous(breaks = seq(500, 8500, 500)) +
   theme_minimal() +
   scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) +
   geom_col(
     position = "dodge"
   ) +
   labs( #labelling axis
     x = "Degree",
     y = "Number of Degree Holders"
   ) +
   scale_fill_brewer(palette = "BuPu")

```

```{r}
#| echo: false
#| warning: false

# race_sex_table <- import_clean_data |>
#   select(year, race, sex) |> 
#   table(import_clean_data$sex, import_clean_data$race,
#         import_clean_data$year) |>
#   ftable(race_sex_table)
```



```{r}
#| echo: false
#| warning: false

by_year_total <- filter_degree |>
  group_by(year) |> 
  count()

transpose_totals <- data.frame(t(by_year_total))

rownames(transpose_totals) <- c("", "Totals")

transpose_totals_w_titles <- transpose_totals |> 
  row_to_names(row_number = 1)

total_respondents_table <- transpose_totals_w_titles |> 
  kable(caption = "Total number of respondents, education data") |>
  kable_styling(
    latex_options = c("striped", "hold_position"),
    font_size=10) |> 
  row_spec(0, bold=T)

total_respondents_table

```



```{r}
#| echo: false
#| warning: false

by_year_sex <- filter_degree |> 
  select(degree, year, sex) |>
  group_by(degree, year, sex) |> 
  count(degree)

filter_year_1998_male <- by_year_sex |>
  filter(year == 1998 && sex == "MALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_1998_female <- by_year_sex |>
  filter(year == 1998 && sex == "FEMALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2000_male <- by_year_sex |>
  filter(year == 2000 && sex == "MALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2000_female <- by_year_sex |>
  filter(year == 2000 && sex == "FEMALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2002_male <- by_year_sex |>
  filter(year == 2002 && sex == "MALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2002_female <- by_year_sex |>
  filter(year == 2002 && sex == "FEMALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2004_male <- by_year_sex |>
  filter(year == 2004 && sex == "MALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2004_female <- by_year_sex |>
  filter(year == 2004 && sex == "FEMALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2006_male <- by_year_sex |>
  filter(year == 2006 && sex == "MALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2006_female <- by_year_sex |>
  filter(year == 2006 && sex == "FEMALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2008_male <- by_year_sex |>
  filter(year == 2008 && sex == "MALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2008_female <- by_year_sex |>
  filter(year == 2008 && sex == "FEMALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2010_male <- by_year_sex |>
  filter(year == 2010 && sex == "MALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2010_female <- by_year_sex |>
  filter(year == 2010 && sex == "FEMALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2012_male <- by_year_sex |>
  filter(year == 2012 && sex == "MALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2012_female <- by_year_sex |>
  filter(year == 2012 && sex == "FEMALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2014_male <- by_year_sex |>
  filter(year == 2014 && sex == "MALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2014_female <- by_year_sex |>
  filter(year == 2014 && sex == "FEMALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2016_male <- by_year_sex |>
  filter(year == 2016 && sex == "MALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2016_female <- by_year_sex |>
  filter(year == 2016 && sex == "FEMALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2018_male <- by_year_sex |>
  filter(year == 2018 && sex == "MALE") |> 
  ungroup() |> 
  select(degree, n)

filter_year_2018_female <- by_year_sex |>
  filter(year == 2018 && sex == "FEMALE") |> 
  ungroup() |> 
  select(degree, n)

merge_list <- list(
  filter_year_1998_male,
  filter_year_1998_female,
  filter_year_2000_male,
  filter_year_2000_female,
  filter_year_2002_male,
  filter_year_2002_female,
  filter_year_2004_male,
  filter_year_2004_female,
  filter_year_2006_male,
  filter_year_2006_female,
  filter_year_2008_male,
  filter_year_2008_female,
  filter_year_2010_male,
  filter_year_2010_female,
  filter_year_2012_male,
  filter_year_2012_female,
  filter_year_2014_male,
  filter_year_2014_female,
  filter_year_2016_male,
  filter_year_2016_female,
  filter_year_2018_male,
  filter_year_2018_female)

my_merge <- function(df1, df2) {
  merge(df1, df2, by = "degree")
}

education_by_sex_data <- Reduce(my_merge, merge_list)


```



```{r}
#| echo: false
#| warning: false

# knitr::kable(education_by_sex_data,
#              col.names = c("Education", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F"))

kbl(education_by_sex_data,
    caption = "Education details of respondents by sex from 1998 - 2018",
    col.names = c("Education", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F"),
    align = c(rep("l", 1), rep("c"))) |> 
  add_header_above(c(" ",
                     "1998" = 2,
                     "2000" = 2,
                     "2002" = 2,
                     "2004" = 2,
                     "2006" = 2,
                     "2008" = 2,
                     "2010" = 2,
                     "2012" = 2,
                     "2014" = 2,
                     "2016" = 2,
                     "2018" = 2 )) |>
  kable_styling(
    latex_options = c("striped", "hold_position"),
    font_size=6, full_width = F) |>
  column_spec(1, width = "2cm") |>
  column_spec(2:23, width = "0.2cm") |> 
  row_spec(0, bold=T)


```



```{r}
#| echo: false
#| warning: false

by_race <- filter_degree |> 
  select(year, degree, race) |>
  # filter(degree != "Less than high school") |>
  # filter(degree != "High school") |>
  group_by(race, degree) |>
  count(year)

```


```{r}
#| echo: false
#| warning: false
#| label: degree_by_race
#| fig-cap: Number of people with post-secondary education.
#| fig-align: center
#| fig-width: 6

by_race |>
  ggplot(aes(x = year, y = n, color = degree)) +
  geom_point() +
  geom_line() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 65, vjust = 0.6)) +
  facet_wrap(
    ~race,
    ncol = 1,
    scale="free_y"
  ) +
  scale_x_continuous(breaks = seq(1998, 2018, 2)) +
  labs(
    x = "Year",
    y = "Number of degree holders by race",
    color = "race"
  ) +
  scale_colour_discrete(labels = function(x) str_wrap(x, width = 5))



```




\newpage


# References


